apiVersion: v1
kind: ServiceAccount
metadata:
  name: prow-build
  namespace: test-pods
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::855606814420:role/node-e2e-tests
  name: node-e2e-tests
  namespace: test-pods
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::855606814420:role/kubetest2/provider-aws-test-role
  name: provider-aws-test-role
  namespace: test-pods
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::209411653980:role/aws-shared-testing-role
  name: aws-shared-testing-role
  namespace: test-pods
