---
apiVersion: v1
kind: Namespace
metadata:
  name: k8s-infra-test-pods
---
apiVersion: v1
kind: Namespace
metadata:
  name: test-pods
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
