---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: k8s-infra-cherrypick-robot-github-token
spec:
  data:
  - remoteRef:
      key: k8s-infra-cherrypick-robot-github-token
    secretKey: token
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubernetes-public
# ---
# apiVersion: kubernetes-client.io/v1
# kind: ExternalSecret
# metadata:
#   name: cluster-api-provider-digitalocean-quayio
#   namespace: default
# spec:
#   backendType: gcpSecretsManager
#   projectId: k8s-infra-prow-build-trusted
#   data:
#   - key: capdo-quayio-registry-secret
#     name: config.json
#     version: latest
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kubeconfig-eks-prow-build-cluster
spec:
  data:
  - remoteRef:
      key: eks-prow-build-cluster-kubeconfig
    secretKey: kubeconfig
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-infra-prow
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kubeconfig-k8s-infra-kops-prow-build
spec:
  data:
  - remoteRef:
      key: k8s-infra-kops-prow-build-kubeconfig
    secretKey: kubeconfig
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-infra-prow
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth-token
spec:
  data:
  - remoteRef:
      key: oauth-token
    secretKey: oauth
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-infra-prow
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: slack-token
spec:
  data:
  - remoteRef:
      key: slack-token
    secretKey: token
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-infra-prow
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hmac-token
spec:
  data:
  - remoteRef:
      key: hmac-token
    secretKey: hmac
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-infra-prow
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-oauth-config
spec:
  data:
  - remoteRef:
      key: github-oauth-config
    secretKey: secret
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-infra-prow
