apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prow

resources:
- prowjob-crd.yaml
- cherrypicker.yaml
- crier.yaml
- deck.yaml
- external-secrets.yaml
- gce-ssd-retain_storageclass.yaml
- ghproxy.yaml
- halogen.yaml
- hook.yaml
- horologium.yaml
- ing_ingress.yaml
- ingress.yaml
- managedcertificates.yaml
- needs-rebase.yaml
- pipeline.yaml
- prow-controller-manager.yaml
- pushgateway.yaml
- sinker.yaml
- statusreconciler.yaml
- tide.yaml
- trusted_serviceaccounts.yaml

patches:
- patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: ignored
    spec:
      replicas: 0
  target:
    kind: Deployment
    # These deployments talk to Kubernetes clusters and we don't want to do that yet
    name: hook|prow-controller-manager|crier|deck|sinker
