apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

resources:
- cherrypicker.yaml
- crier.yaml
- deck.yaml
- external-secrets.yaml
- gce-ssd-retain_storageclass.yaml
- ghproxy.yaml
- hook.yaml
- horologium.yaml
- gateway.yaml
- needs-rebase.yaml
- pipeline.yaml
- prow-controller-manager.yaml
- pushgateway.yaml
- sinker.yaml
- statusreconciler.yaml
- tide.yaml
- monitoring.yaml
- trusted_serviceaccounts.yaml
