# permissions that are required beyond roles/owner to effectively manage
# our GCP organization, at least according to the role bindings that have
# been manually added to org admins thus far
title: Organization Admin
description: Access to administer all resources belonging to the organization
name: organization.admin
include:
  roles:
  # specific billing permissions we need
  # TODO(spiffxp): should we just use billing.admin? or save this for GCP accounting group?
  # maybe for resourceAssociations.create
  - roles/billing.user
  # for billing.accounts.create (to create a budget for a project)
  - roles/billing.creator
  # maybe for budgets.*, this also offers accounts.updateUsageExportSpec
  - roles/billing.costsManager

  # resourcemanager.* permissions missing from roles/owner
  # for resourcemanager.folders.*
  - roles/resourcemanager.folderAdmin
  # for resourcemanager.organizations.*
  - roles/resourcemanager.organizationAdmin
  # for resourcemanager.projects.create
  - roles/resourcemanager.projectCreator

  # for storage.buckets.(get|update|(get|set)IamPolicy)
  - roles/storage.admin
  permissionRegexes:
  # to ensure storage.buckets.* is all we get from roles/storage.admin
  - ^billing.
  - ^orgpolicy.
  - ^resourcemanager.
  - ^storage.buckets.
