# allow principals with roles/secretmanager.admin on specific secrets
# to manage those secrets via the GCP console
title: Secret Manager Secret Lister
description: Allows viewing and listing Secret Manager secret resources
name: secretmanager.secretLister
include:
  roles:
  - roles/secretmanager.viewer
exclude:
  permissionRegexes:
  - ^secretmanager.(locations|versions)
  - getIamPolicy$
