extraObjects:
 -  apiVersion: external-secrets.io/v1beta1
    kind: ClusterSecretStore
    metadata:
      name: k8s-infra-prow
    spec:
      provider:
        gcpsm:
          projectID: k8s-infra-prow
 -  apiVersion: external-secrets.io/v1beta1
    kind: ClusterSecretStore
    metadata:
      name: kubernetes-public
    spec:
      provider:
        gcpsm:
          projectID: kubernetes-public
 -  apiVersion: external-secrets.io/v1beta1
    kind: ClusterSecretStore
    metadata:
      name: k8s-infra-prow-build-trusted
    spec:
      provider:
        gcpsm:
          projectID: k8s-infra-prow-build-trusted
