---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: ghproxy
  labels:
    app: ghproxy
spec:
  ports:
    - name: main
      port: 80
      protocol: TCP
      targetPort: 8888
  selector:
    app: ghproxy
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: ghproxy-metrics
  namespace: default
  labels:
    app: ghproxy
spec:
  selector:
    app: ghproxy
  ports:
    - name: metrics
      port: 9090
  loadBalancerIP: 34.121.239.242 # k8s-infra-prow-build-trusted/ghproxy-metrics
  type: LoadBalancer
