apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: atlantis-vcs
spec:
  data:
    - secretKey: webhook
      remoteRef:
        key: atlantis-webhook-k8s-io-repo
    - secretKey: token
      remoteRef:
        key: k8s-infra-ci-robot-github-token
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-infra-prow
