apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atlantis
spec:
  destination:
    namespace: atlantis
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes/gke-utility/atlantis
    repoURL: https://github.com/borg-land/k8s.io
    targetRevision: deploy-atlantis
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
