apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  destination:
    name: gke-utility
    namespace: istio-system
  project: default
  sources:
    - chart: base
      repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: 1.23.2
    - path: config/crd/experimental
      repoURL: https://github.com/kubernetes-sigs/gateway-api
      targetRevision: v1.1.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
spec:
  destination:
    name: gke-utility
    namespace: istio-system
  project: default
  sources:
    - chart: istiod
      repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: 1.23.2
      helm:
        values: |
          global:
            hub: gcr.io/istio-release
            istiod:
              enableAnalysis: true
          meshConfig:
            accessLogFile: /dev/stdout
            enablePrometheusMerge: true
            protocolDetectionTimeout: 5s
            enableTracing: true
            extensionProviders:
            - name: "oauth2-proxy"
              envoyExtAuthzHttp:
                service: "oauth2-proxy.oauth2-proxy.svc.cluster.local"
                port: "80"
                headersToDownstreamOnDeny:
                  - content-type
                  - set-cookie
                headersToUpstreamOnAllow:
                  - authorization
                  - cookie
                  - path
                  - x-*
                includeHeadersInCheck:
                  - authorization
                  - cookie
                  - user-agent
            defaultConfig:
              gatewayTopology:
                numTrustedProxies: 2
          telemetry:
            enabled: true
            v2:
              prometheus:
                enabled: true
                wasmEnabled: false
    - path: kubernetes/gke-utility/istio-system
      repoURL: https://github.com/borg-land/k8s.io
      targetRevision: istio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
