apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring
spec:
  goTemplate: true
  generators:
    - clusters:
        selector:
          matchLabels:
            clusterType: 'utility'
  template:
    metadata:
      name: 'monitoring-{{ .name }}'
    spec:
      destination:
        namespace: monitoring
        server: "{{ .server }}"
      project: default
      sources:
        - chart: kube-prometheus-stack
          repoURL: https://prometheus-community.github.io/helm-charts
          targetRevision: 62.3.1
          helm:
            releaseName: monitoring
            valueFiles:
              - $values/kubernetes/{{ .name }}/helm/monitoring.yaml
        - repoURL: https://github.com/borg-land/k8s.io
          targetRevision: observability-stack
          ref: values
        - path: kubernetes/{{ .name }}/monitoring/
          repoURL: https://github.com/borg-land/k8s.io
          targetRevision: observability-stack
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
