grafana:
  enabled: true
prometheus:
  thanosService:
    enabled: true
  prometheusSpec:
    thanos:
      image: quay.io/thanos/thanos:v0.36.1
      listenLocal: false
      logLevel: debug
      objectStorageConfig:
        secret:
          type: GCS
          config:
            bucket: k8s-io-thanos
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false

# These endpoints aren't scrapable on GKE
coreDns:
  enabled: false
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
