apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: https://argo.k8s.io
  application.instanceLabelKey: infra.k8s.io/instance
  resource.compareoptions: |
    ignoreAggregatedRoles: true
  resource.customizations: |
    admissionregistration.k8s.io/MutatingWebhookConfiguration:
      ignoreDifferences: |
        jqPathExpressions:
        - '.webhooks[]?.clientConfig.caBundle'
  resource.exclusions: |
    - apiGroups:
        - cilium.io
      kinds:
        - CiliumIdentity
      clusters:
        - "*"
  kustomize.buildOptions: --load-restrictor LoadRestrictionsNone --enable-alpha-plugins
