apiVersion: v1
kind: Secret
metadata:
  name: kubernetes-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/kubernetes
  name: kubernetes
  type: git
