apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- github.com/argoproj/argo-cd/manifests/ha/cluster-install?ref=v2.11.2
- extras.yaml
- clusters.yaml

patches:
- path: argocd-cmd-params-cm.yaml
- path: argocd-cm.yaml
- path: argocd-cm-rbac.yaml
- path: argocd-sa.yaml
